/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logisticaigu;

import Controladoras.ControladoraPaquete;
import Controladoras.ControladoraViaje;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import logisticalogica.Paquete;
import logisticalogica.Viaje;

/**
 *
 * @author ULTRA
 */
public class HojaDeRuta extends javax.swing.JFrame {

    /**
     * Creates new form HojaDeRuta
     */
        private  ControladoraPaquete ctrlPaquete;
        private  ControladoraViaje ctrlViaje;
        private String rolUsuario;
    public HojaDeRuta(String rolUsuario) {
        initComponents();
        this.rolUsuario = rolUsuario;
        this.ctrlPaquete = new ControladoraPaquete();
        ctrlViaje = new ControladoraViaje();
        cargarViajesActivos();       
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Abre el JFrame en pantalla completa

        // Crear un renderizador personalizado para los encabezados de las columnas
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.LEFT); // Alinear a la izquierda     horizontalmente
        headerRenderer.setVerticalAlignment(SwingConstants.CENTER); // Centrar verticalmente
        headerRenderer.setFont(new Font("Arial", Font.PLAIN, 18)); // Establecer la fuente a Arial 18  
        // Aplicar el renderizador personalizado a los encabezados de las columnas
        jTable1.getTableHeader().setDefaultRenderer(headerRenderer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Viaje", "Modelo", "Patente", "Provincia de origen", "Localidad de origen", "Provincia de destino", "Localidad de destino", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hoja de ruta - Seleccionar viaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1026, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(100, 100, 100)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        int viajeID = (int) jTable1.getValueAt(selectedRow, 0);
        abrirHojaDeRutaPaquetes(viajeID);
    } else {
        // Crear un JLabel para personalizar el mensaje
        JLabel selecviaje = new JLabel("Por favor, seleccione un viaje.");
        // Establecer la fuente del JLabel
        selecviaje.setFont(new Font("Arial", Font.PLAIN, 18));
        // Mostrar el cuadro de diálogo de información con el JLabel personalizado y el título personalizado
        JOptionPane.showMessageDialog(null, selecviaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Menu atras = new Menu(rolUsuario);
       atras.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
private void abrirHojaDeRutaPaquetes(int viajeID) {
    List<Paquete> paquetesPlanificados = ctrlPaquete.obtenerPaquetesPlanificadosPorViaje(viajeID);
    if (paquetesPlanificados.isEmpty()) {
        // Crear un JLabel para personalizar el mensaje
        JLabel nopaqueplanificado = new JLabel("No hay paquetes planificados para este viaje.");
        // Establecer la fuente del JLabel
        nopaqueplanificado.setFont(new Font("Arial", Font.PLAIN, 18));
        // Mostrar el cuadro de diálogo de información con el JLabel personalizado y el título personalizado
        JOptionPane.showMessageDialog(null, nopaqueplanificado, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Obtener el modelo y la patente del vehículo seleccionado
        String modeloVehiculo = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
        String patenteVehiculo = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 2);

        // Pasar el modelo y la patente al crear una instancia de HojaDeRutaPaquetes
        HojaDeRutaPaquetes hojaDeRutaPaquetes = new HojaDeRutaPaquetes(viajeID, modeloVehiculo, patenteVehiculo, rolUsuario);
        hojaDeRutaPaquetes.setVisible(true);
        dispose();
    }
}

private void cargarViajesActivos() {
    List<Viaje> viajesActivos = ctrlViaje.obtenerViajesActivos();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Limpiar la tabla antes de cargar nuevos datos
    
    // Definir el formato de fecha
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
    for (Viaje viaje : viajesActivos) {
        // Obtener los nombres de las provincias y localidades
        String provinciaOrigen = viaje.getOrigen().getNombre();
        String localidadOrigen = viaje.getLocalidadOrigen().getNombre();
        String provinciaDestino = viaje.getDestino().getNombre();
        String localidadDestino = viaje.getLocalidadDestino().getNombre();
        
        // Formatear la fecha
        String fecha = dateFormat.format(viaje.getFecha());
        
        // Crear una fila con los datos adecuados
        Object[] fila = {
            viaje.getViajeID(),
            viaje.getVehiculo().getMarca().getModelo(),
            viaje.getVehiculo().getPatente(),
            provinciaOrigen,
            localidadOrigen,
            provinciaDestino,
            localidadDestino,
            fecha
        };
        model.addRow(fila);
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
