/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logisticaigu;

import Controladoras.ControladoraMantenimiento;
import Controladoras.ControladoraMantenimientoRealizado;
import Controladoras.ControladoraParteDiario;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import logisticalogica.Mantenimiento;
import logisticalogica.MantenimientoRealizado;
import logisticalogica.ParteDiario;
import logisticalogica.Vehiculo;
import logisticaigu.AvisoMantenimiento;


public class ParteDiarioIGU extends javax.swing.JFrame {
    private Vehiculo vehiculoSeleccionado;
    private ControladoraParteDiario controladoraPD = new ControladoraParteDiario();
    private ControladoraMantenimiento controladoraMante = new ControladoraMantenimiento();
    private int kmMantenimiento = 10000; // Puedes asignar el valor que corresponda
    private ControladoraMantenimientoRealizado controlmanterealizado = new ControladoraMantenimientoRealizado();
   private String rolUsuario;
    /**
     * Creates new form ParteDiarioIGU
     */
    public ParteDiarioIGU(Vehiculo vehiculoSeleccionado, String rolUsuario) {
         initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH); // Abre el JFrame en pantalla completa
    this.vehiculoSeleccionado = vehiculoSeleccionado; 
    this.controladoraMante = controladoraMante;  // Inicializar la controladoraMante
    this.rolUsuario = rolUsuario;
    Date fechaActual = new Date();
        
        // Establecer la fecha actual en el JCalendar
        jCalendar1.setDate(fechaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar parte diario - Ingresar fecha y kilometros");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Km recorridos:");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCalendar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(100, 100, 100)
                        .addComponent(jButton2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(182, 182, 182)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       guardarParteDiario();

    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       SeleccionVehiculoPD atras = new SeleccionVehiculoPD(rolUsuario);
        atras.setVisible(true);
        dispose(); // Cierra la pantalla actual
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jCalendar1PropertyChange

    /**
     * @param args the command line arguments
     */
    
private void guardarParteDiario() {
    try {
        // Obtener la fecha y km recorridos desde los campos del formulario
        Date fecha = jCalendar1.getDate();
        int kmRecorridos = Integer.parseInt(jTextField1.getText());
        
        // Verificar si se proporcionaron los kilómetros recorridos
        String kmRecorridosText = jTextField1.getText().trim();
        if (kmRecorridosText.isEmpty()) {
            // Crear un JLabel para personalizar el mensaje
            JLabel kmrecorridos = new JLabel("Por favor, ingresa los kilómetros recorridos.");
            // Establecer la fuente del JLabel
            kmrecorridos.setFont(new Font("Arial", Font.PLAIN, 18));

            // Mostrar el mensaje de diálogo con el JLabel personalizado
            JOptionPane.showMessageDialog(this, kmrecorridos, "Error", JOptionPane.ERROR_MESSAGE);

            return; // Detener el proceso si los kilómetros no están presentes
        }

        // Verificar si los kilómetros recorridos son un número válido
        try {
            kmRecorridos = Integer.parseInt(kmRecorridosText);
        } catch (NumberFormatException ex) {
            // Crear un JLabel para personalizar el mensaje
            JLabel kmrecorridosvalido = new JLabel("Por favor, ingresa una cantidad válida para los kilómetros recorridos.");
            // Establecer la fuente del JLabel
            kmrecorridosvalido.setFont(new Font("Arial", Font.PLAIN, 18));

            // Mostrar el mensaje de diálogo con el JLabel personalizado
            JOptionPane.showMessageDialog(this, kmrecorridosvalido, "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener el proceso si los kilómetros no son un número válido
        }

        // Verificar si ya existe un ParteDiario para el Vehiculo
        ParteDiario parteDiarioExistente = controladoraPD.obtenerParteDiarioExistente(vehiculoSeleccionado);

        if (parteDiarioExistente != null) {
            // Si ya existe, sumar los km actuales a los existentes
            int kmTotales = parteDiarioExistente.getKm() + kmRecorridos;
            parteDiarioExistente.setFecha(fecha);
            parteDiarioExistente.setKm(kmTotales);
            controladoraPD.actualizarParteDiario(parteDiarioExistente);
            // Crear un JLabel para personalizar el mensaje
            JLabel partediarioact = new JLabel("Parte diario actualizado correctamente");
            // Establecer la fuente del JLabel
            partediarioact.setFont(new Font("Arial", Font.PLAIN, 18));

            // Mostrar el mensaje de diálogo con el JLabel personalizado
            JOptionPane.showMessageDialog(this, partediarioact, "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Verificar si se superaron los 10000 km y actualizar el mantenimiento
            Mantenimiento mantenimientoExistente = controladoraMante.obtenerMantenimientoExistente(vehiculoSeleccionado);
            if (mantenimientoExistente != null) {
                // Actualizar el mantenimiento existente con los nuevos km
                controladoraMante.actualizarMantenimiento(mantenimientoExistente, kmTotales);

                // Comparar los km del ParteDiario y el último Mantenimiento Realizado
                int kmDesdeUltimoMantenimiento = obtenerKmDesdeUltimoMantenimiento();
                if (kmDesdeUltimoMantenimiento > 10000) {
                    // Mostrar una alerta de mantenimiento
                    // Crear un JLabel para personalizar el mensaje
                    JLabel realizarmante = new JLabel("El vehículo ha superado los 10000 km desde el último mantenimiento realizado. Se recomienda realizar un nuevo mantenimiento.");
                    // Establecer la fuente del JLabel
                    realizarmante.setFont(new Font("Arial", Font.PLAIN, 18));

                    // Mostrar el mensaje de diálogo con el JLabel personalizado
                    JOptionPane.showMessageDialog(this, realizarmante, "Alerta de mantenimiento", JOptionPane.WARNING_MESSAGE);
                }
                // Crear un JLabel para personalizar el mensaje
                String messageText = "Mantenimiento actualizado. Kilómetros totales: " + kmTotales;
                JLabel manteactualizado = new JLabel(messageText);
                // Establecer la fuente del JLabel
                manteactualizado.setFont(new Font("Arial", Font.PLAIN, 18));

                // Mostrar el mensaje de diálogo con el JLabel personalizado
                JOptionPane.showMessageDialog(this, manteactualizado, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Si no hay un mantenimiento existente, crear uno nuevo
                generarMantenimiento(kmTotales);
            }
        } else {
            // Si no existe, crear un nuevo ParteDiario
            ParteDiario nuevoParteDiario = new ParteDiario();
            nuevoParteDiario.setFecha(fecha);
            nuevoParteDiario.setKm(kmRecorridos);
            nuevoParteDiario.setVehiculo(vehiculoSeleccionado);
            controladoraPD.guardarpartediario(nuevoParteDiario);
            // Crear un JLabel para personalizar el mensaje
            JLabel partediarioguardado = new JLabel("Parte diario guardado correctamente");
            // Establecer la fuente del JLabel
            partediarioguardado.setFont(new Font("Arial", Font.PLAIN, 18));

            // Mostrar el mensaje de diálogo con el JLabel personalizado
            JOptionPane.showMessageDialog(this, partediarioguardado, "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Agregar un mensaje de confirmación para informar al usuario
            // Crear un JLabel para personalizar el mensaje
            JLabel partediariocreado = new JLabel("Se ha creado un nuevo parte diario para el vehículo.");
            // Establecer la fuente del JLabel
            partediariocreado.setFont(new Font("Arial", Font.PLAIN, 18));

            // Mostrar el mensaje de diálogo con el JLabel personalizado
            JOptionPane.showMessageDialog(this, partediariocreado, "Nuevo Parte Diario", JOptionPane.INFORMATION_MESSAGE);

            // Verificar si se superaron los 10000 km y generar un mantenimiento
            if (kmRecorridos > kmMantenimiento) {
                generarMantenimiento(kmRecorridos);
            }
        }
    // Crear un JLabel para personalizar el mensaje
    JLabel seguirpartediario = new JLabel("¿Desea seguir haciendo parte diario?");
    // Establecer la fuente del JLabel
    seguirpartediario.setFont(new Font("Arial", Font.PLAIN, 18));

    // Especificar las opciones de los botones
    Object[] options = {"Sí", "No"};

    // Mostrar el cuadro de diálogo de confirmación con opciones personalizadas
    int respuesta = JOptionPane.showOptionDialog(this, seguirpartediario, "Confirmación",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

    if (respuesta == JOptionPane.YES_OPTION) {
        // Si el usuario elige seguir, volver a la pantalla SeleccionVehiculoPD
        SeleccionVehiculoPD atras = new SeleccionVehiculoPD(rolUsuario);
        atras.setVisible(true);
        dispose(); // Cierra la pantalla actual
    } else {
        // Si el usuario elige no seguir, volver al menú (reemplaza con tu lógica específica)
        Menu menu = new Menu(rolUsuario);
        menu.setVisible(true);
        dispose(); // Cierra la pantalla actual
    }

        
    } catch (NumberFormatException ex) {
        // Manejar error de conversión de número
        // Crear un JLabel para personalizar el mensaje
        JLabel validarkm = new JLabel("Por favor, ingresa una cantidad válida para los kilómetros recorridos.");
        // Establecer la fuente del JLabel
        validarkm.setFont(new Font("Arial", Font.PLAIN, 18));

        // Mostrar el mensaje de diálogo con el JLabel personalizado
        JOptionPane.showMessageDialog(this, validarkm, "Error", JOptionPane.ERROR_MESSAGE);
    }
    catch (Exception ex) {
        // Manejar otros errores
        // Crear un JLabel para personalizar el mensaje
        JLabel messageLabel = new JLabel("Error al guardar el parte diario. Verifica los datos ingresados.");
        // Establecer la fuente del JLabel
        messageLabel.setFont(new Font("Arial", Font.PLAIN, 18));

        // Mostrar el mensaje de diálogo con el JLabel personalizado
        JOptionPane.showMessageDialog(this, messageLabel, "Error", JOptionPane.ERROR_MESSAGE);
    }
}




private int obtenerKmDesdeUltimoMantenimiento() {
    // Obtener el último mantenimiento realizado
    MantenimientoRealizado ultimoMantenimiento = controlmanterealizado.obtenerUltimoMantenimientoRealizado(vehiculoSeleccionado);

    if (ultimoMantenimiento != null) {
        // Obtener el último ParteDiario
        ParteDiario parteDiarioExistente = controladoraPD.obtenerParteDiarioExistente(vehiculoSeleccionado);

        if (parteDiarioExistente != null) {
            // Calcular los kilómetros recorridos desde el último mantenimiento
            return parteDiarioExistente.getKm() - ultimoMantenimiento.getKmMantenimiento();
        } else {
            // Si no hay ParteDiario existente, se asume que es la primera vez
            return 0;
        }
    } else {
        // Si no hay mantenimientos realizados previos, se asume que es la primera vez
        return 0;
    }
}

private void generarMantenimiento( int kmTotales) {
    // Crear un objeto Mantenimiento
    Mantenimiento nuevoMantenimiento = new Mantenimiento();
    nuevoMantenimiento.setKm(kmTotales);
    nuevoMantenimiento.setVehiculo(vehiculoSeleccionado);

    // Guardar el Mantenimiento
    controladoraMante.guardarmantenimiento(nuevoMantenimiento);

    // Mostrar una alerta
    // Crear un JLabel para personalizar el mensaje
    JLabel manteauto = new JLabel("Se ha generado automáticamente un mantenimiento. Kilómetros totales: " + kmTotales);
    // Establecer la fuente del JLabel
    manteauto.setFont(new Font("Arial", Font.PLAIN, 18));
    // Mostrar el cuadro de diálogo de advertencia con el JLabel personalizado y el título predeterminado
    JOptionPane.showMessageDialog(this, manteauto, "Alerta de mantenimiento", JOptionPane.WARNING_MESSAGE);
}








    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
