/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logisticaigu;

import Controladoras.ControladoraLocalidad;
import Controladoras.ControladoraPaquete;
import Controladoras.ControladoraProvincia;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import logisticalogica.Cliente;
import logisticalogica.Localidad;
import logisticalogica.Paquete;
import logisticalogica.Provincia;

/**
 *
 * @author ULTRA
 */
public class RegistrarPaquete extends javax.swing.JFrame {
    private ControladoraPaquete controladoraPaquete;
    private Paquete paquete;
    private Paquete paqueteTemporal; // Agregar una variable para almacenar el paqueteTemporal
    private String rolUsuario; 
    private ControladoraLocalidad controladoralocalidad;
    private ControladoraProvincia controladoraprovincia;
        private List<Provincia> provincias ;

    /**
     * Creates new form RegistrarEnvio
     */
    public RegistrarPaquete(String rolUsuario) {
        initComponents();
        controladoraprovincia = new ControladoraProvincia();
        controladoralocalidad = new ControladoraLocalidad();
        controladoraPaquete = new ControladoraPaquete();
        this.rolUsuario = rolUsuario; 
        llenarComboBoxProvincias();
        llenarComboBoxProvinciasDestino();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Abre el JFrame en pantalla completa
    
    jComboBox1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String nombreProvincia = (String) jComboBox1.getSelectedItem();
            Provincia provinciaSeleccionada = null;
            for (Provincia provincia : provincias) {
                if (provincia.getNombre().equals(nombreProvincia)) {
                    provinciaSeleccionada = provincia;
                    break;
                }
            }
            llenarComboBoxLocalidades(provinciaSeleccionada);
        }
    });
    jComboBox3.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String nombreProvincia = (String) jComboBox3.getSelectedItem();
            Provincia provinciaSeleccionada = null;
            for (Provincia provincia : provincias) {
                if (provincia.getNombre().equals(nombreProvincia)) {
                    provinciaSeleccionada = provincia;
                    break;
                }
            }
            llenarComboBoxLocalidadesDestino(provinciaSeleccionada);
        }
    });
    }
    public void setPaqueteTemporal(Paquete paqueteTemporal) {
        this.paqueteTemporal = paqueteTemporal;
        
    }
    
    private void llenarComboBoxProvincias() {
         provincias = controladoraprovincia.obtenerTodasLasProvincias();
        for (Provincia provincia : provincias) {
            jComboBox1.addItem(provincia.getNombre());
        }
        
    }
    
    // Método para llenar el JComboBox de localidades
    private void llenarComboBoxLocalidades(Provincia provincia) {
        jComboBox2.removeAllItems(); // Limpiar el JComboBox de localidades antes de agregar nuevos elementos
        List<Localidad> localidades = controladoralocalidad.obtenerLocalidadesPorProvincia(provincia);
        for (Localidad localidad : localidades) {
            jComboBox2.addItem(localidad.getNombre());
        }
    }
   private void llenarComboBoxProvinciasDestino() {
    // Limpia los elementos previos si existen
    jComboBox3.removeAllItems();
    for (Provincia provincia : provincias) {
        jComboBox3.addItem(provincia.getNombre());
    }
}

private void llenarComboBoxLocalidadesDestino(Provincia provincia) {
    jComboBox4.removeAllItems();
    if (provincia != null) {
        List<Localidad> localidades = controladoralocalidad.obtenerLocalidadesPorProvincia(provincia);
        for (Localidad localidad : localidades) {
            jComboBox4.addItem(localidad.getNombre());
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registroenvio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registroenvio.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Registroenvio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registroenvio.setText("Registrar paquete - Ingresar envío");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Domicilio de entrega:");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Descripcion:");

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Domicilio de retiro:");

        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Localidad de origen:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Provincia de origen:");

        jComboBox3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Provincia de destino:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Localidad de destino:");

        jComboBox4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(100, 100, 100)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(186, 186, 186)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox3, 0, 240, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registroenvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registroenvio)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Menu atras = new Menu(rolUsuario);
        atras.setVisible(true);
        dispose(); // Cierra la pantalla actual
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   String domicilioEntrega = jTextField3.getText();
    String domicilio = jTextField1.getText();
    String descripcion = jTextField2.getText();

    // Verificar si ambos campos contienen datos
    if (!domicilio.isEmpty() && !descripcion.isEmpty()) {
        // Obtener la provincia de origen seleccionada del combo box
        String nombreProvinciaOrigen = (String) jComboBox1.getSelectedItem();
        Provincia provinciaOrigen = null;
        for (Provincia provincia : provincias) {
            if (provincia.getNombre().equals(nombreProvinciaOrigen)) {
                provinciaOrigen = provincia;
                break;
            }
        }

        // Obtener la localidad de origen seleccionada del combo box
        String nombreLocalidadOrigen = (String) jComboBox2.getSelectedItem();
        Localidad localidadOrigen = null;
        if (provinciaOrigen != null) {
            List<Localidad> localidadesOrigen = controladoralocalidad.obtenerLocalidadesPorProvincia(provinciaOrigen);
            for (Localidad localidad : localidadesOrigen) {
                if (localidad.getNombre().equals(nombreLocalidadOrigen)) {
                    localidadOrigen = localidad;
                    break;
                }
            }
        }

        // Obtener la provincia de destino seleccionada del combo box
        String nombreProvinciaDestino = (String) jComboBox3.getSelectedItem();
        Provincia provinciaDestino = null;
        for (Provincia provincia : provincias) {
            if (provincia.getNombre().equals(nombreProvinciaDestino)) {
                provinciaDestino = provincia;
                break;
            }
        }

        // Obtener la localidad de destino seleccionada del combo box
        String nombreLocalidadDestino = (String) jComboBox4.getSelectedItem();
        Localidad localidadDestino = null;
        if (provinciaDestino != null) {
            List<Localidad> localidadesDestino = controladoralocalidad.obtenerLocalidadesPorProvincia(provinciaDestino);
            for (Localidad localidad : localidadesDestino) {
                if (localidad.getNombre().equals(nombreLocalidadDestino)) {
                    localidadDestino = localidad;
                    break;
                }
            }
        }

        paqueteTemporal = inicializarPaquete(domicilioEntrega, domicilio, descripcion);
        // Guardar provincias y localidades en el paquete temporal
        paqueteTemporal.setOrigen(provinciaOrigen);
        paqueteTemporal.setLocalidadOrigen(localidadOrigen);
        paqueteTemporal.setDestino(provinciaDestino);
        paqueteTemporal.setLocalidadDestino(localidadDestino);

        // Añade mensajes de depuración
        System.out.println("PaqueteTemporal en RegistrarEnvio:");
        mostrarInfoPaqueteTemporal(paqueteTemporal);

        // Crea la instancia de BuscarClientes
        BuscarClientes busqueda = new BuscarClientes(paqueteTemporal, rolUsuario);
        busqueda.setPaqueteTemporal(paqueteTemporal); // Establece el paqueteTemporal
        busqueda.setVisible(true);
        this.dispose(); // Cierra la ventana actual
    } else {
        // Crear un JLabel para personalizar el mensaje
        JLabel completacampos = new JLabel("Por favor, completa todos los campos.");
        // Establecer la fuente del JLabel
        completacampos.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18));
        // Mostrar el cuadro de diálogo de advertencia con el JLabel personalizado y el título personalizado
        JOptionPane.showMessageDialog(this, completacampos, "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void mostrarInfoPaqueteTemporal(Paquete paqueteTemporal) {
    if (paqueteTemporal != null) {
        System.out.println("Código de paquete: " + paqueteTemporal.getCodigo_paquete());
        System.out.println("Domicilio de entrega: " + paqueteTemporal.getDomicilioEntrega());
        // Mostrar otros atributos según sea necesario
    } else {
        System.out.println("paqueteTemporal es nulo.");
    }
}/*
     * @param args the command line arguments
     */
public Paquete inicializarPaquete(String domicilioretiro, String domicilio, String descripcion) {
    Paquete paquete = new Paquete();
    paquete.setDomicilioRetiro(domicilioretiro);
    paquete.setDomicilioEntrega(domicilio);
    paquete.setDescripcion(descripcion);

    StringBuilder codigoPaqueteStr = new StringBuilder();
    for (int i = 0; i < 10; i++) {
        int digitoAleatorio = (int) (Math.random() * 10);
        codigoPaqueteStr.append(digitoAleatorio);
    }

    long codigoPaquete = Long.parseLong(codigoPaqueteStr.toString());

    codigoPaquete = codigoPaquete % Integer.MAX_VALUE;

    int codigoPaqueteInt = (int) codigoPaquete;
    paquete.setCodigo_paquete(codigoPaqueteInt);

    return paquete;
}


   
    public Paquete obtenerPaqueteTemporal() {
    return paqueteTemporal;
}
     public void mostrarVentana() {
        // Código para mostrar la ventana de registro de envío
        // Ajusta según tu implementación
        this.setVisible(true);  // Ajusta según cómo se muestra la ventana en tu aplicación
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registroenvio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
